---
title: "Assessments"
descriptions: |
    Course assessments for DSCI 310: Reproducible and trustworthy workflows for data science.
output:
  distill::distill_article:
    toc: true
---

### Assessment schedule

This course includes a substantial group project component.
You will work in randomly assigned groups of four for the project milestones. 
There are also individual assignments 
that act as stepping stones to the project milestones.
Given that collaboration is so important in data science, 
a portion of your final grade will be an assessment of the evidence you provide 
that you were an effective and productive team member.
A combination of peer evaluation 
and GitHub history will be used to evaluate this.
Your individual knowledge on the course materials 
(concepts and practical skills)
will be evaluated on two summative assessments (midterm and final exam).

Finally, this course is delivered in a blended format, 
with some pre-work (video watching or reading) 
expected to be done before each lecture.
These will be provided in the course Canvas shell.
Each in class lecture session will start with iClicker cloud
questions to probe your understanding of the pre-lecture material
and then we will work through demonstrations 
and exercises in class to build off of this.

In general, assignments will be due 11:59 PM on Saturdays. 
However, in the final week of classes, 
all assignments need to be submitted by the final day of classes, 
thus we have two alternative due dates that week.

| Assessment                                                        | Description                                                                                                                                                                                                                                                                       | Due date                                    | Due Week |
|----------------|------------------------|----------------|----------------|
| [Individual assignment 1](individual_assignment1.html)                                           | Setting up your computer                                                                                                                                                                                                                                                          | 2023/01/20 23:59                            | 2        |
| GitHub username quiz                                              |                                                                                                                                                                                                                                                                                   | 2023/01/20 23:59                            | 2        |
| [Individual assignment 2](individual_assignment2.html)                                           | Version control practice                                                                                                                                                                                                                                                          | 2023/01/27 23:59                            | 3        |
| [Individual assignment 3](individual_assignment3.html)                                           | Dockerfile practice                                                                                                                                                                                                                                                               | 2023/02/10 23:59                            | 5        |
| Mid-term exam                                                     | The midterm is a summative assessment: <https://www.cmu.edu/teaching/assessment/basics/formativesummative.html>                                                                                      | 2023/02/12-2023/02/16 (Exact date/time TBD) | 6        |
| [Milestone 1](milestone1.html)                                                       | Question, data & rough draft of analysis in one monolithic literate code document, reproducible environment                                                                                                                    | 2023/03/02 23:59                            | 8        |
| [Individual assignment 4](individual_assignment4.html)                                           | Reproducible reports practice                                                                                                                                                                                                                                                     | 2023/03/09 23:59                            | 9        |
| [Milestone 2](milestone2.html)                                                       | literate code document broken into scripts and a report & data analysis pipeline to stitch everything together, and upgrade to a container computational environment                                                                                                                                                                       | 2023/03/16 23:59                            | 10       |
| [Milestone 3](milestone3.html)                                                       |  functions abstracted to a file/module & tests, function documentation                                                                                                       | 2023/03/30 23:59                            | 12       |
| [Peer review](peer-review.html)                                                       | review of another group's project                                                                                                                                                                                                                                                 | 2023/04/06 23:59                            | 13       |
| [Individual assignment 5](individual_assignment5.html)                                          | Packaging practice                                                                                                                                                                                                                                                                | 2023/04/06 23:59                            | 13       |
| Final project                                                     | package & CI (the full monty package - including docs)                                                                                                                                                                                                                            | 2023/04/11 23:59                            | 14       |
| Team work                                                         | Reflection of how the group worked together, as well as individual performance                                                                                                                                                                                                    | 2023/04/12 23:59                            | 14       |
| Final exam (**You must pass the final exam to pass the course.**) | The Final Exam will include all the material covered in all the components of the course. This is a summative assessment: <https://www.cmu.edu/teaching/assessment/basics/formativesummative.html> | TBD 

