---
title: "Computer setup"
description: |
  Computer requirements and software installation instructions for DSCI 310.
output:
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

These instructions will walk you through how to install the required Data Science software stack for DSCI 310. Before starting with the installation instructions, ensure that your laptop meets our program requirements. **If your computer does not meet the requirements please reach out to the teaching team on Piazza and describe how it does not. We will work to accomodate you where we can.**

## Laptop requirements

 - Runs one of the following operating systems: Ubuntu 20.04, macOS (version 11.4.x or higher), Windows 10 (version 2004, 20H2, 21H1 or higher).
    - When installing Ubuntu, checking the box "Install third party..." will (among other things) install proprietary drivers, which can be helpful for wifi and graphics cards.
- Can connect to networks via a wireless connection for on campus work
- Has access to an internet connection that is fast and stable enough for video calling and conducting online quizzes
- Has at least 30 GB disk space available
- Has at least 4 GB of RAM
- Uses a 64-bit CPU
- Is at most 6 years old (4 years old or newer is recommended)
- Uses English as the default language
- Student user has full administrative access to the computer

## Software installation instructions

Please click the appropriate link below to view the installation instructions for your operating system:

- [macOS arm](install_stack_mac.html) 
- [Ubuntu](install_stack_ubuntu.html)
- [Windows](install_stack_windows.html)

 *The following people contributed to these instructions: Daniel Chen, Anmol Jawandha, Tomas Beuzen, Rodolfo Lourenzutti, Joel Ostblom, Arman Seyed-Ahmadi, Florencia D'Andrea, and Tiffany Timbers.*
