---
title: "Individual assignment 5"
subtitle: Packaging
---

## Motivation

The purpose of this assignment is to ensure that everyone
gains hands-on practice creating software packages in R or Python
(or both for bonus points)!
This will help prepare you to work on
and complete your group project for this course.

## Exercise instructions

This assignment you will follow the tutorial to create a toy/practice package
using the language you are using for your course project.
Follow the instructions in the chapters linked to below.
Use the code they provide for the package functions.

### Make an R package:

- Read through and follow the instructions in [The Whole Game](https://r-pkgs.org/whole-game.html) to create a toy/practice package in the R programming language. Push all your work to GitHub.com in a repository under your personal username.

### And/or make a Python package:

- Read through and follow the instructions in [How to package a Python](https://py-pkgs.org/03-how-to-package-a-python) to create a toy/practice package in the Python programming language. Note - you only need to publish your package to TestPyPI, not PyPI. Push all your work to GitHub.com in a repository under your personal username.


## Submission Instructions

You will submit a PDF to Gradescope for this individual assignment that includes:

1.  the URL of the GitHub.com repository containing your toy/practice package in the Python programming language
2.  the URL of the GitHub.com repository containing your toy/practice package in the R programming language

## Rubric

This assignment will be graded for completion as follows:

|Grade | Description |
|------|-------------|
| 110% | A complete and working toy R package, as well as a complete and working toy Python package |
| 100% | A complete and working toy R or Python package |
| 75%  | A complete but non-working toy R or Python package |
| 50%  | A complete but non-working toy R or Python package |
| 50%  | An incomplete but non-working toy R or Python package |
| 0%   | The assignment was not attempted. |
